apiVersion: v1
kind: Service
metadata:
  name: stock-generator
spec:
  type: NodePort
  selector:
    app: stock-generator
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
